apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: elasticsearch
  name: elasticsearch
spec: 
  ports:
    - name: http
      port: 9200
      protocol: TCP
    - name: transport
      port: 9300
      protocol: TCP
  selector: 
    name: elasticsearch
