apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels: 
    name: elasticsearch
spec: 
  containers: 
    - resources:
      image: elasticsearch:2
      name: elasticsearch
      ports: 
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
      volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /usr/share/elasticsearch/data
  volumes:
    - name: elasticsearch-persistent-storage
      awsElasticBlockStore:
        volumeID: vol-bf47b10d
        fsType: ext4
