apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: pacuna/myapp:0.9
      ports:
        - containerPort: 80
      env:
        - name: PASSENGER_APP_ENV
          value: production
    - name: myapp-db
      image: postgres:9.4
      ports:
        - containerPort: 8000
      env:
        - name: POSTGRES_PASSWORD
          value: secretpassword
