webapp:
  build: .
  container_name: myapp
  working_dir: /home/app/webapp
  environment:
    - PASSENGER_APP_ENV=development
    - VIRTUAL_HOST=myapp.dev.com
  links:
    - db
    - es 
  volumes:
    - .:/home/app/webapp
  volumes_from:
    - gems_container
dbdata:
  image: postgres:9.4
  container_name: myapp-data
  environment:
    - POSTGRES_PASSWORD=secretpassword
  volumes:
    - /var/lib/mysql
  command: /bin/true
db:
  image: postgres:9.4
  container_name: myapp-db
  environment:
    - POSTGRES_PASSWORD=secretpassword
  volumes_from:
    - dbdata

esdata:
  image: elasticsearch:2.2
  container_name: myapp-es-data
  volumes:
    - /var/lib/elasticsearch
  command: /bin/true
es:
  image: elasticsearch:2.2
  container_name: myapp-es
  volumes_from:
    - esdata
