# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abb142f5897e58ed719d8e1d8a8bfb7594e6d1445edfede43503e1315c493e5784f91c23779179366894f5d357d3d3ec63f441401da91c0e1f38f0aec0b9bdbd

test:
  secret_key_base: c4772af84331d8bc482780fb1e6dc4fbb9be9d8aea5be6cff601ddd3d9459671130d62d7b40e77919483fd7e90e1c7cf598940154d819456958a2fb2b1e0a9d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 39d61c36b1fb25649ba688b8bd2de964d1f0fd5e78c34aa5487c4574d74fd14d77fd62cf1d445d9d3ee0af7e8252bc7c853432d4ff08f6f9716df82280dd9067
